Repository mumprod/hr-design-system-handlebars, pull requests merged in 2021-11, with the labels that each got.

#57 Dpe 1221 service nav & icons überarbeiten
  src/stories/views/components/Header/Burger.hbs
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/ServiceLogo.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Header/navigation.json
  src/stories/views/components/base/image/icon.hbs
  tailwind.config.js
Labels: minor

#59 Service icons neu
  .storybook/preview-head.html
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/videopodcast.svg
  src/assets/icons/icons/svgmap/wetter.svg
  src/stories/views/components/Header/BrandNavigation/BrandNavigation.hbs
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/Search/QuickSearchButton.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
Labels: minor

#61 Dpe 1224 alpine js bug with tabbing through hidden items
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/Search/QuickSearchButton.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceLogo.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
Labels: performance

#64 Feature/storybook update
  package-lock.json
  package.json
Labels: skip-release

#66 print cached module size
  .github/workflows/release.yml
Labels: patch

#67 replaces reading npm cache with
  .github/workflows/release.yml
Labels: patch

#69 adds version entry in changelog
  CHANGELOG.md
Labels: patch

#70 Feature/test release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: minor

#72 test commit
  src/stories/views/components/Button.hbs
Labels: minor

#73 test commit
  src/stories/views/components/Button.hbs
Labels: minor

#76 Alle svgs und die entsprechenden optimierungs Skripte sind aus dem Delivery übernommen
  gulpfile.js
  package.json
  src/assets/icons/unweather/regiomap.min.svg
  src/assets/icons/unweather/regiomap.src.svg
  src/assets/icons/weather/regiomap.min.svg
  src/assets/icons/weather/regiomap.src.svg
  src/assets/icons/weather/regiomap_regions_cities.min.svg
  src/assets/icons/weather/regiomap_regions_cities.src.svg
  src/assets/icons/weather/regiomap_topo.min.svg
  src/assets/icons/weather/regiomap_topo.src.svg
Labels: minor

#78 to stay compatible with old components
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/verkehr-ds.svg
  src/assets/icons/icons/svgmap/verkehr.svg
  src/assets/icons/icons/svgmap/videopodcast-ds.svg
  src/assets/icons/icons/svgmap/videopodcast.svg
  src/assets/icons/icons/svgmap/wetter-ds.svg
  src/assets/icons/icons/svgmap/wetter.svg
  src/stories/views/components/Header/navigation.json
  src/stories/views/components/Header/navigation2.json
  src/stories/views/components/Header/navigation3.json
  src/stories/views/components/Header/serviceNavigationData.json
Labels: minor

#79 Feature/svgmin update
  gulpfile.js
  src/assets/icons/404/svgmap.min.svg
  src/assets/icons/epg/svgmap.min.svg
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/publictransport/svgmap.min.svg
  src/assets/icons/traffic/svgmap.min.svg
  src/assets/icons/weather/svgmap.min.svg
Labels: minor

#80 BUGFIX: svgmap for hr3 isn't correctly generated
  gulpfile.js
  src/assets/brand/hessenschau/icons/logo/svgmap.min.svg
  src/assets/brand/hr3/icons/logo/svgmap.min.svg
  src/assets/brand/you-fm/icons/logo/svgmap.min.svg
Labels: bug

#81 Dpe 1220 sub nav der section nav im desktop view part 2
  .storybook/preview.js
  src/assets/tailwind.css
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/Header.stories.mdx
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Header/navigation2.json
  src/stories/views/components/Header/navigation3.json
  tailwind.config.js
Labels: minor

#84 adds logos for cluster-teaser
  src/assets/icons/cluster-teaser/svgmap.min.svg
  src/assets/icons/cluster-teaser/svgmap/boerse_ard_de.svg
  src/assets/icons/cluster-teaser/svgmap/hessenschau_de.svg
  src/assets/icons/cluster-teaser/svgmap/sportschau.svg
  src/assets/icons/cluster-teaser/svgmap/tagesschau-sw.svg
  src/assets/icons/cluster-teaser/svgmap/tagesschau_de.svg
Labels: minor
