Repository mumprod/hr-design-system-handlebars, pull requests merged in 2021-09, with the labels that each got.

#30 Frontify data structure improvement service nav
  src/stories/views/components/Menu/Navigation.stories.mdx
  src/stories/views/components/Menu/ServiceNavigation.hbs
  src/stories/views/components/Menu/ServiceNavigation.stories.mdx
  src/stories/views/components/Menu/ServiceNavigationFlyout.hbs
  src/stories/views/components/Menu/ServiceNavigationFlyout.stories.mdx
  src/stories/views/components/Menu/ServiceNavigationItem.hbs
  src/stories/views/components/Menu/ServiceNavigationItem.stories.mdx
  src/stories/views/components/Menu/data.json
  src/stories/views/components/Menu/serviceIconData.json
  src/stories/views/components/Menu/serviceNavigationData.json
Labels: minor

#31 changes order of files to copy
  scripts/build.js
Labels: patch

#32 run all scripts in build task sequentially
  package.json
Labels: patch

#34 adds comment in front of theme selectors
  src/assets/css/tailwind.css
Labels: patch

#35 small change to build a release
  src/assets/css/tailwind.css
Labels: patch

#39 fixed columns template so it is compatible with delivery now
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs
  src/stories/views/components/Header/serviceNavigationData.json
Labels: patch

#41 Some tailwind stuff for the navi
  .storybook/withThemeDecorator.js
  src/stories/views/components/Header/BrandNavigation/BrandNavigation.hbs
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.stories.mdx
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/Header.stories.mdx
  src/stories/views/components/Header/SectionNavigation/SectionNavigation.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigation.stories.mdx
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.stories.mdx
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigation.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigation.stories.mdx
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.stories.mdx
  src/stories/views/components/Header/navigation.json
Labels: minor

#42 icon.hbs for storybook
  build/helpers/replaceTokens.js
  build/helpers/resourceUrl.js
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/logo/svgmap.min.svg
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/base/image/icon.hbs
Labels: minor

#43 Dpe 1153 brand navigation
  package-lock.json
  package.json
  src/stories/views/components/Header/BrandNavigation/BrandNavigation.hbs
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs
  src/stories/views/components/Header/Header.hbs
  tailwind.config.js
Labels: enhancement, minor, dependencies

#49 Feature/webpack feature loader
  .storybook/main.js
  .storybook/preview.js
  build/webpack/feature-loader/initializer/domElementList.js
  build/webpack/feature-loader/initializer/domElementList.test.js
  build/webpack/feature-loader/initializer/feature.js
  build/webpack/feature-loader/initializer/feature.test.js
  build/webpack/feature-loader/initializer/featureList.js
  build/webpack/feature-loader/initializer/featureList.test.js
  build/webpack/feature-loader/initializer/initializer.js
  build/webpack/feature-loader/initializer/initializer.test.js
  build/webpack/feature-loader/initializer/loader.js
  build/webpack/feature-loader/plugin/ContextReplacement.js
  build/webpack/feature-loader/plugin/DependenciesResolver.js
  build/webpack/feature-loader/plugin/FlatContextMap.js
  build/webpack/feature-loader/plugin/FlatContextMap.test.js
  build/webpack/feature-loader/plugin/FlatContextPlugin.js
  scripts/build.js
  src/stories/views/components/Button.hbs
  src/stories/views/components/foo.feature.js
  src/stories/views/components/generic/hrQueryNew.js
Labels: minor

#50 Dpe 956 styling und funktion burger/section nav
  build/helpers/getRandom.js
  build/helpers/nextRandom.js
  src/assets/tailwind.css
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigation.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.stories.mdx
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Header/navigation.json
  tailwind.config.js
Labels: minor
