Repository mumprod/hr-design-system-handlebars, pull requests merged in 2021-12, with the labels that each got.

#86 Dpe 964 scroll verhalten haupt navigation
  .storybook/preview.js
  src/stories/views/components/Header/Burger.hbs
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
  src/stories/views/components/Header/ServiceLogo.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Page/Page.hbs
  src/stories/views/components/Page/Page.stories.mdx
  tailwind.config.js
Labels: minor

#88 Feature/resource url helper
  build/helpers/resourceUrl.js
  src/stories/views/base/tracking/clickTracking.feature.js
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs
  src/stories/views/components/Header/Burger.hbs
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/Header.stories.mdx
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Page/Page.stories.mdx
  src/stories/views/components/base/image/icon.hbs
  src/stories/views/components/base/link.hbs
Labels: bug

#89 Feature/storybook update
  .storybook/main.js
  package-lock.json
  package.json
Labels: skip-release

#90 updates deprecated features according to
  .storybook/main.js
  package.json
  src/stories/views/components/Header/BrandNavigation/BrandNavigation.stories.mdx
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.stories.mdx
  src/stories/views/components/Header/Header.stories.mdx
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.stories.mdx
  src/stories/views/components/Header/Search/QuickSearchButton.stories.mdx
  src/stories/views/components/Header/Search/QuickSearchForm.stories.mdx
  src/stories/views/components/Header/SectionNavigation/SectionNavigation.stories.mdx
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.stories.mdx
  src/stories/views/components/Header/ServiceNavigation/ServiceList.stories.mdx
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.stories.mdx
  src/stories/views/components/Label.stories.mdx
  src/stories/views/components/Page/Page.stories.mdx
Labels: skip-release
