Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-06, with the labels that each got.

#241 adds support for detect scroll initiated by user or browser
  src/stories/views/components/site_header/header_alpine.js
Labels: patch

#253 Feature/dpe 1651
  .storybook/main.js
  package-lock.json
  package.json
Labels: skip-release

#254 changes z-indexes to 10000 and above
  src/stories/views/components/site_header/header.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
  src/stories/views/components/site_header/service_navigation/service_list.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
  tailwind.config.js
Labels: patch

#257 Feature/dpe 1655
  package-lock.json
  package.json
  postcss.config.js
  src/assets/css/custom-base.css
  src/assets/css/custom-components.css
  src/assets/css/custom-utilities.css
  src/assets/tailwind.css
  src/stories/conventions-and-datastructure.stories.mdx
  tailwind.config.js
Labels: minor
