Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-02, with the labels that each got.

#117 Navi: Element State "Focus" stylen
  src/assets/tailwind.css
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs
  src/stories/views/components/Header/Search/QuickSearchForm.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceLogo.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/base/link.hbs
Labels: patch

#118 Navi: Element State "Focus" stylen
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/ServiceLogo.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Page/Page.stories.mdx
Labels: patch

#122 Dpe-1400 Tablet View: Flyouts 50% bis zum Rand
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Header/navigation4.json
  src/stories/views/components/Page/Page.stories.mdx
  tailwind.config.js
Labels: patch

#129 Feature/frontify6 31
  package-lock.json
  package.json
  postcss.config.js
Labels: minor

#132 - arrows are position correctly also without JS
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
Labels: patch

#136 position:absolute for sectionNavWrapper
  src/stories/views/components/Header/Burger.hbs
  src/stories/views/components/Header/Header.hbs
  tailwind.config.js
Labels: bug

#137 Feature/svg optimization docs
  src/stories/SvgOptimization.stories.mdx
Labels: documentation

#139 navIsVisible store holds information if Navigation is open ore closed
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigation.hbs
Labels: patch
