Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-05, with the labels that each got.

#224 Feature/dpe 1550
  .storybook/main.js
  .storybook/preview.js
  build/scripts/build.js
  build/scripts/jsoninclude.js
  config.js
  gulpfile.js
  package-lock.json
  package.json
  src/assets/fixtures/teaser/teaser_comment.json
  src/assets/fixtures/teaser/teaser_labels.inc.json
  src/assets/fixtures/teaser/teaser_standard_lg_serif.json
  src/assets/fixtures/teaser/teaser_standard_md_serif.json
  src/assets/fixtures/teaser/teaser_standard_sm_serif.json
  src/assets/fixtures/teaser/teaser_standard_xl_serif.json
  src/assets/fixtures/teaser/teaser_standard_xxl_serif.json
  src/assets/fixtures/teaser/teaser_standard_xxl_serif_comments.json
  src/assets/fixtures/teaser/teaser_standard_xxl_serif_label.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/Colors.stories.mdx
  src/stories/Fixtures.stories.mdx
  src/stories/Introduction.stories.mdx
  src/stories/SvgOptimization.stories.mdx
  src/stories/Typography.stories.mdx
  src/stories/conventions-and-datastructure.stories.mdx
  src/stories/views/components/Teaser/data/teasers.json
  src/stories/views/components/Teaser/data/ticker_label.json
  src/stories/views/components/Teaser/fixtures/teaser-standard-lg-serif.json
  src/stories/views/components/Teaser/fixtures/teaser-standard-md-serif.json
  src/stories/views/components/Teaser/fixtures/teaser-standard-sm-serif.json
  src/stories/views/components/Teaser/fixtures/teaser-standard-xl-serif.json
  src/stories/views/components/Teaser/fixtures/teaser-standard-xxl-serif.json
  src/stories/views/components/Teaser/fixtures/teaser_comment.json
  src/stories/views/components/Teaser/fixtures/teaser_commentLink.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_lg_serif.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_md_serif.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_sm_serif.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_xl_serif.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_xxl_serif copy.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_xxl_serif.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_xxl_serif_comments.json
  src/stories/views/components/Teaser/fixtures/teaser_standard_xxl_serif_label.json
  src/stories/views/components/Teaser/fixtures/xxlTeaserStandard--serif.json
  src/stories/views/components/Teaser/fixtures/xxlTeaserStandard--serifLabel.json
  src/stories/views/components/Teaser/teaser-standard.stories.mdx
Labels: minor

#227 Feature/dpe 1550
  src/stories/Fixtures.stories.mdx
  src/stories/views/components/Teaser/teaser-standard.stories.mdx
Labels: documentation

#231 Externalise script from header.hbs & renaming of header components
  .storybook/preview.js
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/base/load_dynamic.hbs
  src/stories/views/components/header/anchor_navigation/anchor_navigation.hbs
  src/stories/views/components/header/anchor_navigation/featurebox_anchor.hbs
  src/stories/views/components/header/brandNavigationData.json
  src/stories/views/components/header/brand_navigation/brand_navigation.hbs
  src/stories/views/components/header/brand_navigation/brand_navigation.stories.mdx
  src/stories/views/components/header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/header/brand_navigation/brand_navigation_item.stories.mdx
  src/stories/views/components/header/burger.hbs
  src/stories/views/components/header/header.hbs
  src/stories/views/components/header/header_.stories.mdx
  src/stories/views/components/header/header_alpine.js
  src/stories/views/components/header/navigation.json
  src/stories/views/components/header/navigation2.json
  src/stories/views/components/header/navigation3.json
  src/stories/views/components/header/navigation4.json
  src/stories/views/components/header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/header/navigation_flyout/navigation_flyout.stories.mdx
  src/stories/views/components/header/navigation_flyout/navigation_flyout_column.hbs
  src/stories/views/components/header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/header/search/quick_search_button.hbs
  src/stories/views/components/header/search/quick_search_button.stories.mdx
  src/stories/views/components/header/search/quick_search_form.hbs
  src/stories/views/components/header/search/quick_search_form.stories.mdx
  src/stories/views/components/header/sectionNavigationData.json
  src/stories/views/components/header/section_navigation/section_navigation.hbs
  src/stories/views/components/header/section_navigation/section_navigation.stories.mdx
  src/stories/views/components/header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/header/section_navigation/section_navigation_item.stories.mdx
  src/stories/views/components/header/serviceNavigationData.json
  src/stories/views/components/header/service_logo.hbs
  src/stories/views/components/header/service_navigation/service_list.hbs
  src/stories/views/components/header/service_navigation/service_list.stories.mdx
  src/stories/views/components/header/service_navigation/service_navigation_item.hbs
  src/stories/views/components/header/service_navigation/service_navigation_item.stories.mdx
  src/stories/views/components/page/page.hbs
  src/stories/views/components/page/page.stories.mdx
Labels: minor

#233 renamed folders header and search to site_header and navigation_search
  .storybook/preview.js
  src/stories/views/components/base/load_dynamic.hbs
  src/stories/views/components/page/page.hbs
  src/stories/views/components/page/page.stories.mdx
  src/stories/views/components/site_header/anchor_navigation/anchor_navigation.hbs
  src/stories/views/components/site_header/anchor_navigation/featurebox_anchor.hbs
  src/stories/views/components/site_header/brandNavigationData.json
  src/stories/views/components/site_header/brand_navigation/brand_navigation.hbs
  src/stories/views/components/site_header/brand_navigation/brand_navigation.stories.mdx
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.stories.mdx
  src/stories/views/components/site_header/burger.hbs
  src/stories/views/components/site_header/header.hbs
  src/stories/views/components/site_header/header_.stories.mdx
  src/stories/views/components/site_header/header_alpine.js
  src/stories/views/components/site_header/navigation.json
  src/stories/views/components/site_header/navigation2.json
  src/stories/views/components/site_header/navigation3.json
  src/stories/views/components/site_header/navigation4.json
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.stories.mdx
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_column.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_button.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_button.stories.mdx
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.stories.mdx
  src/stories/views/components/site_header/sectionNavigationData.json
  src/stories/views/components/site_header/section_navigation/section_navigation.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation.stories.mdx
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.stories.mdx
  src/stories/views/components/site_header/serviceNavigationData.json
  src/stories/views/components/site_header/service_logo.hbs
  src/stories/views/components/site_header/service_navigation/service_list.hbs
  src/stories/views/components/site_header/service_navigation/service_list.stories.mdx
  src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation_item.stories.mdx
Labels: minor

#236 - removed css classes from responsive_image.hbs
  src/stories/views/components/base/image/responsive_image.hbs
  src/stories/views/components/teaser/teaser_alternativ.hbs
  src/stories/views/components/teaser/teaser_standard.hbs
Labels: patch

#237 - fixed label call in teaser_heading.hbs
  build/helpers/loca.js
  src/assets/fixtures/teaser/teaser_labels.inc.json
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_label.json
  src/stories/views/components/teaser/fixtures/teaser_poster_md_label.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_label.json
Labels: patch
