Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-08, with the labels that each got.

#290 Dpe 1675 Download Teaser
  build/helpers/loca.js
  src/assets/fixtures/teaser/teaser_alternative_100_serif_download.json
  src/assets/fixtures/teaser/teaser_alternative_50_serif_download.json
  src/assets/fixtures/teaser/teaser_labels.inc.json
  src/assets/fixtures/teaser/teaser_standard_100_serif_download.json
  src/assets/fixtures/teaser/teaser_standard_50_serif_download.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_download.json
  src/stories/views/components/teaser/teaser_alternativ.stories.mdx
  src/stories/views/components/teaser/teaser_standard.stories.mdx
Labels: minor

#285 better wording in mdx
  src/stories/views/components/site_header/header.stories.mdx
Labels: patch

#292 BUGFIX: The items in a group are not
  src/stories/views/components/grid/grid_group.hbs
Labels: minor

#293 Feature/dpe 1567
  src/stories/views/components/audio/audio_element.hbs
  src/stories/views/components/base/image/responsive_image.hbs
  src/stories/views/components/base/link.hbs
  src/stories/views/components/base/loadSSI.hbs
  src/stories/views/components/base/load_dynamic.hbs
  src/stories/views/components/grid/grid.hbs
  src/stories/views/components/grid/grid_group.hbs
  src/stories/views/components/grid/grid_item.hbs
  src/stories/views/components/label/label.hbs
  src/stories/views/components/label/label.stories.mdx
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/site_header/service_navigation/service_list.hbs
  src/stories/views/components/teaser/components/teaser_byline.hbs
  src/stories/views/components/teaser/components/teaser_comments.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/components/teaser_heading.stories.mdx
  src/stories/views/components/teaser/components/teaser_image.hbs
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/components/teaser_text.stories.mdx
  src/stories/views/components/teaser/components/teaser_title.hbs
  src/stories/views/components/teaser/components/teaser_title.stories.mdx
  src/stories/views/components/teaser/components/teaser_title_classes.hbs
  src/stories/views/components/teaser/components/teaser_topline.hbs
  src/stories/views/components/teaser/components/teaser_topline.stories.mdx
  src/stories/views/components/teaser/teaser_alternativ.hbs
  src/stories/views/components/teaser/teaser_alternativ.stories.mdx
  src/stories/views/components/teaser/teaser_alternativ_av.stories.mdx
  src/stories/views/components/teaser/teaser_logic/teaser_logic.hbs
  src/stories/views/components/teaser/teaser_logic/teaser_logic.ssi.hbs
  src/stories/views/components/teaser/teaser_poster.hbs
  src/stories/views/components/teaser/teaser_standard.hbs
  src/stories/views/components/video/livestream/video_livestream.hbs
  src/stories/views/components/video/video_element.hbs
Labels: patch

#294 Feature/dpe 1567
  src/stories/views/components/base/image/responsive_image.hbs
Labels: bug

#301 Dpe 1689 teaser content navi
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_100.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_50.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_autosuggest_100.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_autosuggest_50.json
  src/assets/fixtures/teaser/teaser_content_nav_list_100.json
  src/assets/fixtures/teaser/teaser_content_nav_list_25.json
  src/assets/fixtures/teaser/teaser_content_nav_list_33.json
  src/assets/fixtures/teaser/teaser_content_nav_list_50.json
  src/assets/fixtures/teaser/teaser_content_nav_list_66.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_100.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_25.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_33.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_50.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_66.json
  src/stories/views/base/autosuggest/autoSuggest.feature.js
  src/stories/views/components/base/menu/dropdown.hbs
  src/stories/views/components/base/menu/o-dropdown.hbs
  src/stories/views/components/base/menu/toggleClass.feature.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/site_header/header_alpine.js
  src/stories/views/components/teaser/content_nav/teaser_content_nav.hbs
  src/stories/views/components/teaser/content_nav/teaser_content_nav.stories.mdx
  src/stories/views/components/teaser/fixtures/cluster_teaser_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_100_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_50.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_50.json
  src/stories/views/components/teaser/fixtures/teaser_cluster.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_50.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_autosuggest100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_autosuggest_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_autosuggest_50.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_25.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_33.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_50.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_66.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_25.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_33.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_50.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_66.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight_2.json
  src/stories/views/components/teaser/fixtures/teaser_index.json
  tailwind.config.js
Labels: minor

#302 bugfix
  src/stories/views/components/base/menu/dropdown.hbs
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/teaser/content_nav/teaser_content_nav.stories.mdx
Labels: patch

#303 moved script to header_alpine.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/site_header/header_alpine.js
Labels: patch

#307 BUGFIX: mediaPlayerButton is selected correctly.
  src/stories/views/components/mediaplayer/mediaplayerLoader.feature.js
Labels: bug

#310 Content nav part6
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/site_header/header_alpine.js
  src/stories/views/components/teaser/content_nav/teaser_content_nav.stories.mdx
  tailwind.config.js
Labels: patch

#311 adds autosuggest to list and flow, several refactoring
  src/assets/fixtures/teaser/teaser_content_nav_flow_100.json
  src/assets/fixtures/teaser/teaser_content_nav_list_100.json
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/site_header/header_alpine.js
  src/stories/views/components/teaser/content_nav/teaser_content_nav.stories.mdx
  src/stories/views/components/teaser/fixtures/teaser_content_nav_flow_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_100.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_contentNav.json
Labels: patch
