Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-07, with the labels that each got.

#259 jsoninclude used in header now
  src/assets/fixtures/site_header/brandNavigation.inc.json
  src/assets/fixtures/site_header/sectionNavigation.inc.json
  src/assets/fixtures/site_header/sectionNavigation_mit_submenu.inc.json
  src/assets/fixtures/site_header/serviceNavigation.inc.json
  src/assets/fixtures/site_header/serviceNavigation_mit_warnung.inc.json
  src/assets/fixtures/site_header/site_header_default.json
  src/assets/fixtures/site_header/site_header_mit_submenu.json
  src/assets/fixtures/site_header/site_header_mit_warnung.json
  src/stories/views/components/site_header/fixtures/site_header_default.json
  src/stories/views/components/site_header/fixtures/site_header_mit_submenu.json
  src/stories/views/components/site_header/fixtures/site_header_mit_warnung.json
  src/stories/views/components/site_header/header.stories.mdx
Labels: patch

#261 Dpe 1588
  .storybook/main.js
  .storybook/preview.js
  src/assets/fixtures/teaser/teaser_standard_25_serif_av_consumption.json
  src/stories/views/base/tracking/atiHelperDs.js
  src/stories/views/base/tracking/atiMediaHelperDs.js
  src/stories/views/components/audio/audioElementDs.subfeature.js
  src/stories/views/components/button/button_round.hbs
  src/stories/views/components/externalService/trackingCookieDs.subfeature.js
  src/stories/views/components/foo.feature.js
  src/stories/views/components/generic/hrQueryDs.js
  src/stories/views/components/mediaplayer/mediaplayerLoaderDs.feature.js
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_av_consumption.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_av_consumption copy.json
  src/stories/views/components/teaser/teaser_standard.hbs
  src/stories/views/components/teaser/teaser_standard_av.stories.mdx
  src/stories/views/components/video/livestream/videoLivestreamDs.subfeature.js
  src/stories/views/components/video/videoOnDemandPlayerDs.subfeature.js
  src/stories/views/components/video/video_element.hbs
Labels: patch

#263 fixes zindex of header so overlay doesnt overlay
  src/stories/views/components/site_header/header.hbs
Labels: patch

#265 adds listener for touchmove (mobile)
  src/stories/views/components/site_header/header_alpine.js
Labels: patch

#266 adds detection for scrollbar use
  src/stories/views/components/site_header/header_alpine.js
Labels: patch

#268 refactoring and better component order
  .storybook/preview.js
  src/stories/views/components/site_header/header_alpine.js
Labels: patch

#273 BUGFIX: updates the configuration of the
  gulpfile.js
  src/assets/brand/hr-rundfunkrat/icons/logo/svgmap.min.svg
  src/assets/brand/you-fm/icons/logo/svgmap.min.svg
  src/assets/icons/weather/svgmap.min.svg
Labels: bug

#277 FEATURE: Changes the name of the js feature
  build/webpack/feature-loader/initializer/initializer.js
  src/stories/example.hbs
  src/stories/views/components/Button.hbs
  src/stories/views/components/audio/audio_element.hbs
  src/stories/views/components/base/link.hbs
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
  src/stories/views/components/teaser/tabbox/teaser_tabbox.hbs
  src/stories/views/components/video/livestream/video_livestream.hbs
  src/stories/views/components/video/video_element.hbs
Labels: minor

#276 refactor header.stories.mdx
  .storybook/main.js
  src/assets/images/navi_default.png
  src/assets/images/navi_flyout_section.PNG
  src/assets/images/navi_flyout_service.PNG
  src/assets/images/navi_mobil_burger_open.PNG
  src/assets/images/navi_mobil_default.PNG
  src/assets/images/navi_mobil_scroll_1percent.PNG
  src/assets/images/navi_mobil_scroll_50percent.PNG
  src/assets/images/navi_mobil_search.PNG
  src/assets/images/navi_mobil_search.jpg
  src/assets/images/navi_scroll_50percent.PNG
  src/assets/images/navi_scroll_90percent.PNG
  src/assets/images/navi_tablet.PNG
  src/assets/images/navi_tablet_flyout_service.PNG
  src/assets/images/navi_tablet_scroll_1percent.PNG
  src/assets/images/navi_tablet_scroll_50percent.PNG
  src/assets/tailwind.css
  src/stories/views/components/site_header/header.stories.mdx
  src/stories/views/components/site_header/header_alpine.js
Labels: patch

#279 removes loader from main.js + some more doku
  .storybook/main.js
  src/stories/views/components/site_header/header.stories.mdx
Labels: patch

#286 Feature/dpe 1567
  .storybook/main.js
  build/scripts/build.js
  src/stories/views/base/tracking/atiHelper.subfeature.js
  src/stories/views/base/tracking/atiMediaHelper.subfeature.js
  src/stories/views/components/audio/audioElementDs.subfeature.js
  src/stories/views/components/externalService/trackingCookieDs.subfeature.js
  src/stories/views/components/foo.feature.js
  src/stories/views/components/generic/hrQuery.subfeature.js
  src/stories/views/components/mediaplayer/mediaplayerLoaderDs.feature.js
  src/stories/views/components/video/livestream/videoLivestreamDs.subfeature.js
  src/stories/views/components/video/videoOnDemandPlayerDs.subfeature.js
Labels: minor

#288 FEATURE: All js files that get loaded by
  build/scripts/build.js
Labels: patch

#289 FEATURE: hrQuery is moved out of the components
  .storybook/main.js
  src/stories/views/generic/hrQuery.subfeature.js
Labels: patch
