Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-03, with the labels that each got.

#172 Build/skip tests
  .github/workflows/chromatic.yml
  src/stories/views/components/Button.hbs
Labels: skip-release

#173 Build/skip tests
  .github/workflows/chromatic.yml
  src/stories/views/components/Button.hbs
Labels: skip-release

#174 change bg-color for testing reasons
  src/stories/views/components/Button.hbs
Labels: skip-release

#175 Build/skip tests
  .github/workflows/chromatic.yml
  src/stories/views/components/Button.hbs
Labels: skip-release

#176 Build/skip tests
  .github/workflows/chromatic.yml
Labels: skip-release

#179 FEATURE: configures chromatic to make
  src/stories/views/components/Page/Page.stories.mdx
Labels: documentation

#180 FEATURE: every component gets a
  src/stories/views/components/Header/BrandNavigation/BrandNavigation.hbs
  src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs
  src/stories/views/components/Header/Burger.hbs
  src/stories/views/components/Header/Header.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
  src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs
  src/stories/views/components/Header/Search/QuickSearchButton.hbs
  src/stories/views/components/Header/Search/QuickSearchForm.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigation.hbs
  src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
  src/stories/views/components/Header/ServiceLogo.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
  src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
  src/stories/views/components/Headline.hbs
  src/stories/views/components/Label.hbs
  src/stories/views/components/base/image/icon.hbs
  src/stories/views/components/base/link.hbs
Labels: minor

#184 Build/tailwind
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/assets/tailwind.css
Labels: minor

#185 FEATURE: adds webpackplugin that always saves
  .storybook/main.js
Labels: skip-release

#190 rename class headline--barrier to headline--separator
  src/assets/tailwind.css
  src/stories/views/components/Grid/Grid.hbs
Labels: patch

#194 test
  src/stories/views/components/Button.hbs
Labels: skip-release

#196 testtest
  src/stories/views/components/Button.hbs
Labels: bug

#197 Feature/dpe 1520
  src/stories/views/components/Teaser/teaser.json
Labels: skip-release

#199 DOC: adds installation instructions
  .github/workflows/release.yml
  README.md
Labels: minor

#200 DOCS: adds section to nvm in readme
  README.md
Labels: documentation
