Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-11, with the labels that each got.

#356 using json playlist instead of array
  build/gulp/cache/.gitkeep
  build/handlebars/partials/handlebar-partials.js
  src/assets/brand/_default/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.merged.json
  src/assets/brand/hr-bigband/conf/locatags.merged.json
  src/assets/brand/hr-fernsehen/conf/locatags.merged.json
  src/assets/brand/hr-inforadio/conf/locatags.merged.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.merged.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.merged.json
  src/assets/brand/hr-werbung/conf/locatags.merged.json
  src/assets/brand/hr/conf/locatags.merged.json
  src/assets/brand/hr1/conf/locatags.merged.json
  src/assets/brand/hr2/conf/locatags.merged.json
  src/assets/brand/hr3/conf/locatags.merged.json
  src/assets/brand/hr4/conf/locatags.merged.json
  src/assets/brand/you-fm/conf/locatags.merged.json
  src/assets/fixtures/teaser/teasersPodcastPlaylist.inc.json
  src/assets/js/podcastPlayer.alpine.js
  src/assets/vendor/js/podcast_player.alpine.js
  src/stories/views/components/teaser/fixtures/teaser_podcast_playlist.json
  src/stories/views/components/teaser/podcast/podcast_playbutton.hbs
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
  src/stories/views/components/teaser/podcast/podcast_timedisplay.hbs
Labels: minor

#362 fixes js for multiple contentnavs
  .storybook/preview-head.html
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/site_header/site_header_default.json
  src/assets/vendor/js/content_nav.alpine.js
  src/assets/vendor/js/header.alpine.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/page/page.hbs
  src/stories/views/components/site_header/fixtures/site_header_default.json
  src/stories/views/components/teaser/content_nav/teaser_content_nav.hbs
  tailwind.config.js
Labels: bug

#363 fixes wrong absolute positioning
  build/handlebars/partials/handlebar-partials.js
  src/assets/vendor/js/content_nav.alpine.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
Labels: bug

#366 Feature/dpe 1674
  build/handlebars/helpers/handlebar-helpers.js
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/stage_eventtags.inc.json
  src/assets/fixtures/teaser/stage_teaser.json
  src/assets/fixtures/teaser/stage_teaser_eventtag.json
  src/assets/fixtures/teaser/stage_teaser_program.json
  src/assets/fixtures/teaser/stage_teaser_wide.json
  src/assets/fixtures/teaser/teaser_images.inc.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/assets/images/emmanuel-tjeknavorian-108_v-16to9.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-16to9__medium.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-16to9__medium__extended.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-16to9__retina.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-16to9__small.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-1920to529.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-4to3.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-4to3__medium.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-4to3__retina.jpg
  src/assets/images/emmanuel-tjeknavorian-108_v-4to3__small.jpg
  src/assets/images/greenteams-grafik-100_v-16to9.jpg
  src/assets/images/greenteams-grafik-100_v-16to9__medium.jpg
  src/assets/images/greenteams-grafik-100_v-16to9__medium__extended.jpg
  src/assets/images/greenteams-grafik-100_v-16to9__retina.jpg
  src/assets/images/greenteams-grafik-100_v-16to9__small.jpg
  src/assets/images/greenteams-grafik-100_v-1920to529.jpg
  src/assets/images/greenteams-grafik-100_v-4to3.jpg
  src/assets/images/greenteams-grafik-100_v-4to3__medium.jpg
  src/assets/images/greenteams-grafik-100_v-4to3__retina.jpg
  src/assets/images/greenteams-grafik-100_v-4to3__small.jpg
  src/assets/tailwind.css
  src/stories/views/components/base/load_dynamic.hbs
  src/stories/views/components/event/stage_location.ssi.hbs
  src/stories/views/components/label/label.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/components/teaser_title.hbs
  src/stories/views/components/teaser/components/teaser_title_classes.hbs
  src/stories/views/components/teaser/components/teaser_topline.hbs
  src/stories/views/components/teaser/fixtures/stage_teaser.json
  src/stories/views/components/teaser/fixtures/stage_teaser_eventtag.json
  src/stories/views/components/teaser/fixtures/stage_teaser_program.json
  src/stories/views/components/teaser/fixtures/stage_teaser_wide.json
  src/stories/views/components/teaser/teaser_stage.hbs
  src/stories/views/components/teaser/teaser_stage.stories.mdx
  tailwind.config.js
Labels: minor

#367 fixes some more zindex issues
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
Labels: minor

#368 new markup in page.hbs / some minor fixes
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/page/page.hbs
  src/stories/views/components/teaser/content_nav/teaser_content_nav.hbs
Labels: minor

#369 ...
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/teaser/content_nav/teaser_content_nav.hbs
Labels: minor

#377 Feature/dpe 1837: Downloadteaser
  build/handlebars/partials/handlebar-partials.js
  src/assets/brand/_default/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.merged.json
  src/assets/brand/hr-bigband/conf/locatags.merged.json
  src/assets/brand/hr-fernsehen/conf/locatags.merged.json
  src/assets/brand/hr-inforadio/conf/locatags.merged.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.merged.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.merged.json
  src/assets/brand/hr-werbung/conf/locatags.merged.json
  src/assets/brand/hr/conf/locatags.merged.json
  src/assets/brand/hr1/conf/locatags.merged.json
  src/assets/brand/hr2/conf/locatags.merged.json
  src/assets/brand/hr3/conf/locatags.merged.json
  src/assets/brand/hr4/conf/locatags.merged.json
  src/assets/brand/you-fm/conf/locatags.merged.json
  src/assets/fixtures/teaser/teaser_images.inc.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/components/teaser_byline.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_comments_without_teaserinfo.json
  src/stories/views/components/teaser/fixtures/teaser_group_100.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight_2.json
  src/stories/views/components/teaser/fixtures/teaser_index.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_100_accented.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_100_boxed.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_100_highlighted.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_50_accented.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_two_events.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_multiple_events.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_tabbox.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_two_events.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_audio_livestream.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_podcast.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_standard_66_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_comments.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_label.json
Labels: skip-release

#378 Teasertext shows Copyright for fileDownload
  src/assets/fixtures/teaser/teaser_images.inc.json
Labels: minor

#379 and on it goes..
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_comments_without_teaserinfo.json
  src/stories/views/components/teaser/fixtures/teaser_group_100.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight_2.json
  src/stories/views/components/teaser/fixtures/teaser_index.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_100_accented.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_100_boxed.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_100_highlighted.json
  src/stories/views/components/teaser/fixtures/teaser_indextext_50_accented.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_two_events.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_multiple_events.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_tabbox.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_two_events.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_audio_livestream.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_podcast.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_standard_66_serif_single_event.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_comments.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_label.json
Labels: minor

#380 Feature/dpe 1774: External Link Teaser
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/teaser_alternative_100_serif_link.json
  src/assets/fixtures/teaser/teaser_alternative_50_serif_link.json
  src/assets/fixtures/teaser/teaser_alternative_hero_serif_link.json
  src/assets/fixtures/teaser/teaser_standard_100_serif_link.json
  src/assets/fixtures/teaser/teaser_standard_25_serif_link.json
  src/assets/fixtures/teaser/teaser_standard_33_serif_link.json
  src/assets/fixtures/teaser/teaser_standard_50_serif_link.json
  src/assets/fixtures/teaser/teaser_standard_hero_serif_link.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_video copy.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif copy.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_download copy.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_link copy.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_link copy.json
  src/stories/views/components/teaser/fixtures/teaser_standard_33_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_link copy.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_link.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_link.json
  src/stories/views/components/teaser/teaser_alternativ.stories.mdx
  src/stories/views/components/teaser/teaser_standard.stories.mdx
Labels: minor

#381 Bugfix: Add cacheEntry logic to teaser_logic.ssi.hbs
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/teaser/teaser_logic/teaser_logic.ssi.hbs
Labels: minor

#382 Feature/dpe 1674
  build/handlebars/partials/handlebar-partials.js
  src/assets/css/custom-utilities.css
  src/stories/views/components/event/stage_location.ssi.hbs
  src/stories/views/components/teaser/stage/stage_text.hbs
  src/stories/views/components/teaser/teaser_stage.hbs
  tailwind.config.js
Labels: minor

#383 BUGFIX: Removes css classes from delivery.
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/teaser/teaser_stage.hbs
Labels: bug

#384 FEATURE: adds boxshadow on top of stage
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/teaser/teaser_stage.hbs
  tailwind.config.js
Labels: patch

#386 FEATURE: Renames headlineListOverview property
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/cluster_teaser_extern_100.json
  src/assets/fixtures/teaser/cluster_teaser_extern_33.json
  src/assets/fixtures/teaser/cluster_teaser_extern_50.json
  src/assets/fixtures/teaser/cluster_teaser_ordered_100.json
  src/assets/fixtures/teaser/cluster_teaser_ordered_33.json
  src/assets/fixtures/teaser/cluster_teaser_ordered_50.json
  src/assets/fixtures/teaser/teaser_cluster.inc.json
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_byline.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/fixtures/cluster_teaser_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_100_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_100_image.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33_image.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50_image.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_50.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_50.json
  src/stories/views/components/teaser/fixtures/teaser_cluster.json
Labels: minor

#387 Feature/dpe 1677
  build/handlebars/partials/handlebar-partials.js
  src/assets/tailwind.css
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/components/teaser_title.hbs
  src/stories/views/components/teaser/stage/stage_text.hbs
  tailwind.config.js
Labels: patch

#389 BUGFIX: Title of externalProject is displayed
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/teaser/stage/stage_text.hbs
Labels: minor

#393 FEATURE: Runs partialsToJs script in chromatic
  .github/workflows/chromatic.yml
  .gitignore
  build/handlebars/partials/handlebar-partials.js
Labels: skip-release

#394 Feature/dpe 1671: Program-Teaser in Design-System
  src/assets/fixtures/teaser/teaser_alternative_hero_serif_program.json
  src/assets/fixtures/teaser/teaser_labels.inc.json
  src/assets/fixtures/teaser/teaser_standard_100_serif_program.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/assets/tailwind.css
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/components/teaser_image.hbs
  src/stories/views/components/teaser/components/teaser_lead.hbs
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_l.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_program.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_program.json
  src/stories/views/components/teaser/teaser_alternativ.stories.mdx
  src/stories/views/components/teaser/teaser_standard.stories.mdx
  tailwind.config.js
Labels: minor

#396 Podcast layout issues fixed
  src/assets/fixtures/teaser/teaser_podcast_playlist_50.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_playlist_50.json
  src/stories/views/components/teaser/podcast/podcast-playlist.hbs
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast.stories.mdx
Labels: patch

#398 BUGFIX: Bring back title and topline color and use subline color
  src/stories/views/components/teaser/components/teaser_heading.hbs
Labels: minor

#399 Feature/dpe 1671: Remove not needed code parts for tracking
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/components/teaser_image.hbs
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_program.json
Labels: minor

#400 Remove Brackets from external Link
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_program.json
Labels: minor

#402 Feature/dpe 1671
  src/stories/views/components/teaser/components/teaser_image.hbs
Labels: minor

#403 add margin x and y for teaser media button for program
  src/stories/views/components/teaser/components/teaser_image.hbs
Labels: minor

#406 Feature/dpe 1822: Remove _doTracking, because it is not needed anymore
  src/stories/conventions-and-datastructure.stories.mdx
  src/stories/views/components/base/link.hbs
  src/stories/views/components/mediaplayer/media_player.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/components/teaser_comments.hbs
  src/stories/views/components/teaser/components/teaser_image.hbs
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/teaser_poster.hbs
  src/stories/views/components/teaser/teaser_poster.stories.mdx
Labels: minor

#407 Delete not needed param and add mt-12 to safeList to be sure the css-…
  src/stories/views/components/teaser/group_teaser/group_teaser.hbs
  tailwind.config.js
Labels: minor
