Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-09, with the labels that each got.

#312 adds some of mithras designs
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_100.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_autosuggest_100.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_subgroups.json
  src/assets/fixtures/teaser/teaser_content_nav_flow_100.json
  src/assets/fixtures/teaser/teaser_content_nav_list_100.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_100.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_autosuggest.json
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/content_nav/dropdown.hbs
  src/stories/views/components/site_header/header_alpine.js
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_autosuggest_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_subgroups.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_flow_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_autosuggest.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_contentNav.json
Labels: patch

#313 Content nav part9
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/content_nav/dropdown.hbs
  src/stories/views/components/teaser/content_nav/teaser_content_nav.hbs
Labels: patch

#314 Feature/dpe 1567
  src/stories/views/generic/hrQuery.subfeature.js
Labels: bug

#316 Dpe 1689 content navi next steps
  src/assets/fixtures/teaser/teaser_groups.inc.json
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
  src/stories/views/components/teaser/fixtures/teaser_group_100_contentNav.json
  src/stories/views/components/teaser/group_teaser/group.stories.mdx
  src/stories/views/components/teaser/group_teaser/group_teaser.hbs
Labels: patch

#329 Dpe 1766
  .storybook/preview-head.html
  src/assets/vendor/js/podcastPlayer.alpine.js
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast.stories.mdx
  src/stories/views/components/teaser/podcast/podcast_player.hbs
Labels: minor

#331 Feature/dpe 1567
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/withThemeDecorator.js
  CHANGELOG.md
  README.md
  build/handlebars/handlebars.js
  build/handlebars/helpers/handlebar-helpers.js
  build/handlebars/partials/handlebar-partials.js
  build/helpers/block.js
  build/helpers/case.js
  build/helpers/configProperty.js
  build/helpers/default.js
  build/helpers/defaultIfEmpty.js
  build/helpers/getRandom.js
  build/helpers/if.js
  build/helpers/include.js
  build/helpers/inline-switch.js
  build/helpers/isStorybook.js
  build/helpers/json.js
  build/helpers/loca.js
  build/helpers/nextRandom.js
  build/helpers/partial.js
  build/helpers/replaceTokens.js
  build/helpers/resourceUrl.js
  build/helpers/switch.js
  build/helpers/withParam.js
  build/partials/handlebar-partials-test.js
  config.js
  gulpfile.js
  package-lock.json
  package.json
  src/assets/fixtures/teaser/teaser_groups.inc.json
  src/assets/vendor/js/podcastPlayer.alpine.js
  src/stories/Fixtures.stories.mdx
  src/stories/SvgOptimization.stories.mdx
  src/stories/views/base/tracking/atiHelper.subfeature.js
  src/stories/views/components/base/link.hbs
  src/stories/views/components/button/button_pseudo.hbs
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/externalService/trackingCookie.subfeature.js
  src/stories/views/components/mediaplayer/ardPlayerLoader.subfeature.js
  src/stories/views/components/mediaplayer/media_player.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/components/teaser_comments.hbs
  src/stories/views/components/teaser/components/teaser_image.hbs
  src/stories/views/components/teaser/components/teaser_image_overlay.hbs
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/teaser_logic/teaser_logic.hbs
  src/stories/views/components/teaser/teaser_poster.hbs
  src/stories/views/components/teaser/teaser_standard.hbs
  src/stories/views/components/teaser/teaser_standard_event.hbs
Labels: minor
