Repository mumprod/hr-design-system-handlebars, pull requests merged in 2022-10, with the labels that each got.

#332 Feature/dpe 1567
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  build/handlebars/partials/handlebar-partials.js
  build/helpers/ifCond.js
  build/modernizr/config.json
  build/modernizr/customTests.js
  build/partials/handlebar-partials-test.js
  build/scripts/build.js
  config.js
  gulpfile.js
  package-lock.json
  package.json
  src/assets/js/content_nav_alpine.js
  src/assets/vendor/alpine/header_alpine.js
  src/assets/vendor/modernizr/modernizr.cust.js
  src/assets/vendor/modernizr/modernizr.js
  src/stories/views/base/tracking/clickTracking.feature.js
  src/stories/views/components/teaser/teaser_alternativ.hbs
  tailwind.config.js
Labels: patch

#335 BUGFIX: The image of alternative teasers gets
  build/handlebars/partials/handlebar-partials.js
  src/stories/views/components/teaser/teaser_alternativ.hbs
Labels: bug

#336 Podcast teaser steve
  build/handlebars/partials/handlebar-partials.js
  package-lock.json
  package.json
  src/assets/fixtures/teaser/teaser_podcast.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/pause-button-podcast.svg
  src/assets/icons/icons/svgmap/play-button-podcast.svg
  src/assets/js/podcastPlayer.alpine.js
  src/stories/views/components/label/label.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast.stories.mdx
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  tailwind.config.js
Labels: minor

#337 Dpe 1696 podcast player cosmetics
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/teasers.inc.json
  src/assets/js/podcastPlayer.alpine.js
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/podcast/podcast_player.hbs
Labels: minor

#339 Dpe 1696 podcast player refactoring part2
  build/handlebars/partials/handlebar-partials.js
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/pause-button-podcast.svg
  src/assets/icons/icons/svgmap/play-button-podcast.svg
  src/assets/js/podcastPlayer.alpine.js
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  src/stories/views/components/teaser/podcast/podcast_timedisplay.hbs
  src/stories/views/components/teaser/podcast/podcast_title.hbs
Labels: minor

#340 Dpe 1696 podcast player refactoring part3
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  src/stories/views/components/teaser/podcast/podcast_timedisplay.hbs
Labels: minor

#341 Dpe 1696 podcast player refactoring part4
  build/handlebars/partials/handlebar-partials.js
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/play-button-podcast.svg
  src/assets/icons/icons/svgmap/play-wide.svg
  src/assets/js/podcastPlayer.alpine.js
  src/stories/views/components/teaser/podcast/podcast_playbutton.hbs
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  tailwind.config.js
Labels: minor

#343 Dpe 1696 podcast player refactoring part5
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/teasers.inc.json
  src/assets/js/podcastPlayer.alpine.js
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
Labels: minor

#342 Bugfix/dpe 1567
  .gitignore
  .storybook/preview.js
  README.md
  build/handlebars/handlebars.js
  build/handlebars/helpers/handlebar-helpers.js
  build/handlebars/partials/handlebar-partials.js
  build/scripts/build.js
  config.js
  gulpfile.js
  package-lock.json
  package.json
  src/assets/brand/_default/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.merged.json
  src/assets/brand/hr-bigband/conf/locatags.json
  src/assets/brand/hr-bigband/conf/locatags.merged.json
  src/assets/brand/hr-fernsehen/conf/locatags.json
  src/assets/brand/hr-fernsehen/conf/locatags.merged.json
  src/assets/brand/hr-inforadio/conf/locatags.json
  src/assets/brand/hr-inforadio/conf/locatags.merged.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.merged.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.merged.json
  src/assets/brand/hr-werbung/conf/locatags.json
  src/assets/brand/hr-werbung/conf/locatags.merged.json
  src/assets/brand/hr/conf/locatags.json
  src/assets/brand/hr/conf/locatags.merged.json
  src/assets/brand/hr1/conf/locatags.json
  src/assets/brand/hr1/conf/locatags.merged.json
  src/assets/brand/hr2/conf/locatags.json
  src/assets/brand/hr2/conf/locatags.merged.json
  src/assets/brand/hr3/conf/locatags.json
  src/assets/brand/hr3/conf/locatags.merged.json
  src/assets/brand/hr4/conf/locatags.json
  src/assets/brand/hr4/conf/locatags.merged.json
  src/assets/brand/you-fm/conf/locatags.json
  src/assets/brand/you-fm/conf/locatags.merged.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/mediaplayer/ardPlayerLoader.subfeature.js
  src/stories/views/components/teaser/components/teaser_av_consumption.hbs
  src/stories/views/components/teaser/components/teaser_av_consumption_close_button.hbs
Labels: minor

#346 Dpe 1696 podcastplayer add podcasthoster via each block
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/podcast/podcast_player.hbs
Labels: minor

#347 FEATURE: Uses resourceUrl Helper to access
  .storybook/preview.js
  build/handlebars/partials/handlebar-partials.js
  src/assets/js/empty.js
  src/assets/vendor/js/content_nav.alpine.js
  src/assets/vendor/js/header.alpine.js
  src/assets/vendor/js/podcastPlayer.alpine.js
  src/assets/vendor/js/podcast_player.alpine.js
  src/stories/views/components/teaser/content_nav/teaser_content_nav.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  tailwind.config.js
Labels: minor

#348 FEATURE: Fixtures of content-navs use .inc jsons
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_100.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_50.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_autosuggest_100.json
  src/assets/fixtures/teaser/teaser_content_nav_dropdown_subgroups.json
  src/assets/fixtures/teaser/teaser_content_nav_flow_100.json
  src/assets/fixtures/teaser/teaser_content_nav_flow_autosuggest.json
  src/assets/fixtures/teaser/teaser_content_nav_list_100.json
  src/assets/fixtures/teaser/teaser_content_nav_list_autosuggest.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_100.json
  src/assets/fixtures/teaser/teaser_content_nav_mixed_autosuggest.json
  src/assets/fixtures/teaser/teaser_groups.inc.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_50.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_autosuggest_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_dropdown_subgroups.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_flow_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_flow_autosuggest.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_list_autosuggest.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_100.json
  src/stories/views/components/teaser/fixtures/teaser_content_nav_mixed_autosuggest.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_contentNav.json
Labels: skip-release

#352 Remove Capital I on filename to prevent linux problems
  build/handlebars/partials/handlebar-partials.js
  src/assets/fixtures/teaser/headline_list_item.inc.json
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/publictransport/svgmap.min.svg
  src/assets/icons/traffic/svgmap.min.svg
  src/stories/views/components/teaser/fixtures/teaser_group_100_contentnav.json
Labels: skip-release

#358 Feature/dpe 1806
  build/gulp/cache/.fixturesCache
  build/gulp/cache/.svgMapsCache
  build/gulp/cache/.svgMapsForBrandsCache
  build/gulp/cache/.svgSrcFileCache
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/publictransport/svgmap.min.svg
  src/assets/icons/traffic/svgmap.min.svg
  src/stories/views/components/teaser/components/teaser_title_classes.hbs
Labels: minor
