Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-06, with the labels that each got.

#650 updates tailwind
  yarn.lock
Labels: patch

#651 FEATURE: Use new piano sdk to track clicks
  src/stories/views/base/tracking/atiHelper.subfeature.js
Labels: minor

#652 FEATURE: click action for links navigating to other pages is changed to uxNavigation
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
  src/stories/views/components/tracking/navigation_tracking.hbs
Labels: patch

#660 Tracking Ticker-Teaser
  src/stories/views/components/teaser/ticker/teaser_ticker_footer.hbs
  src/stories/views/components/teaser/ticker/teaser_ticker_standard.hbs
  src/stories/views/components/teaser/ticker/teaser_ticker_timeline.hbs
Labels: bug

#661 Dpe 2314 d
  src/assets/brand/hr3/icons/logo/brandlogo--desk.min.svg
  src/assets/brand/hr3/icons/logo/brandlogo--mobile.min.svg
  src/assets/brand/hr3/icons/logo/svgmap.min.svg
  src/assets/brand/hr3/icons/logo/svgmap/brandlogo--desk.svg
  src/assets/brand/hr3/icons/logo/svgmap/brandlogo--mobile.svg
  src/assets/brand/hr4/icons/logo/brandlogo--desk.min.svg
  src/assets/brand/hr4/icons/logo/brandlogo--mobile.min.svg
  src/assets/brand/hr4/icons/logo/svgmap.min.svg
  src/assets/brand/hr4/icons/logo/svgmap/brandlogo--desk.svg
  src/assets/brand/hr4/icons/logo/svgmap/brandlogo--mobile.svg
Labels: bug

#662 BUGFIX: Revert changes to tracking
  src/stories/views/base/tracking/atiHelper.subfeature.js
Labels: minor
