Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-05, with the labels that each got.

#619 adds sr-only to hbs and hiddenText to json
  src/assets/brand/_default/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.merged.json
  src/assets/brand/hr-bigband/conf/locatags.merged.json
  src/assets/brand/hr-fernsehen/conf/locatags.merged.json
  src/assets/brand/hr-inforadio/conf/locatags.merged.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.merged.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.merged.json
  src/assets/brand/hr-werbung/conf/locatags.merged.json
  src/assets/brand/hr/conf/locatags.merged.json
  src/assets/brand/hr1/conf/locatags.merged.json
  src/assets/brand/hr2/conf/locatags.merged.json
  src/assets/brand/hr3/conf/locatags.merged.json
  src/assets/brand/hr4/conf/locatags.merged.json
  src/assets/brand/you-fm/conf/locatags.merged.json
  src/stories/views/components/site_header/section_navigation/section_navigation_top_topics.hbs
Labels: minor

#620 Feature/dpe 2284
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/base/link.hbs
  src/stories/views/components/base/link.mdx
  src/stories/views/components/base/link.stories.js
  src/stories/views/components/base/link_open.hbs
  src/stories/views/components/base/link_v2.hbs
  src/stories/views/components/button/button.mdx
  src/stories/views/components/button/link_button.hbs
  src/stories/views/components/button/link_button.stories.js
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/event/calendar/event_calendar_event_teaser.hbs
  src/stories/views/components/event/calendar/event_calendar_footer.hbs
  src/stories/views/components/event/event_ticket_button.hbs
  src/stories/views/components/page/fixtures/page_pagination.json
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_top_topics.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/components/teaser_comments.hbs
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/components/teaser_ticker_body.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_100_serif_download.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_download.json
  src/stories/views/components/teaser/podcast/podcast_item_title.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
  src/stories/views/components/teaser/podcast/podcast_title.hbs
  src/stories/views/components/teaser/stage/stage_text.hbs
  src/stories/views/components/teaser/tabbox/group_tabbox.hbs
  src/stories/views/components/teaser/teaser_poster.hbs
  src/stories/views/components/tracking/download_tracking.hbs
  src/stories/views/components/tracking/navigation_tracking.hbs
Labels: minor

#623 uses -primary instead of hardcoded color
  src/assets/css/custom-utilities.css
  src/assets/tailwind.css
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/horizontal_scroll_container/horizontal_scroll_container.hbs
  src/stories/views/components/horizontal_scroll_container/horizontal_scroll_container_example.hbs
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/site_header/burger.hbs
  src/stories/views/components/site_header/header.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_button.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/service_navigation/service_list.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
Labels: minor

#627 DPE-2289 "Regionen" im Burger verrutscht
  src/assets/css/custom-utilities.css
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
Labels: bug

#628 BUGFIX: Teasers use the correct links
  src/stories/views/components/teaser/components/teaser_body.hbs
Labels: minor

#629 Topthemen: Accessibility DPE-1915
  src/stories/views/components/button/top_topics_button.hbs
  src/stories/views/components/horizontal_scroll_container/horizontal_scroll_container.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_top_topics.hbs
Labels: minor

#630 Bugfix/dpe 2295
  gulpfile.js
  src/stories/views/components/pagination/pagination_more_than_three_pages.hbs
  src/stories/views/components/pagination/pagination_only_two_pages.hbs
Labels: minor

#631 BUGFIX: Make trackingInformations ATI conform
  src/assets/fixtures/event/calendar/event_calendar_months.inc.json
  src/stories/views/components/modal/modal.hbs
  src/stories/views/components/teaser/fixtures/teaser_event_calendar_100_serif.json
Labels: bug

#633 BUGFIX: Link in eventcalendar teaser works again
  src/stories/views/components/event/calendar/event_calendar_event_teaser.hbs
Labels: minor

#632 Feature/DPE-2305+DPE-2309
  src/assets/css/custom-utilities.css
  src/assets/fixtures/site_header/sectionNavigation.inc.json
  src/assets/fixtures/site_header/sectionNavigation_mit_submenu_as_flyout.inc.json
  src/assets/fixtures/site_header/serviceNavigation_hr3.inc.json
  src/assets/fixtures/site_header/site_header_mit_submenu_as_flyout.json
  src/assets/fixtures/site_header/site_header_mit_submenu_as_flyout_no_sticky.json
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/nachrichten-ds.svg
  src/assets/icons/icons/svgmap/nachrichten.svg
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/site_header/fixtures/site_header_default copy.json
  src/stories/views/components/site_header/fixtures/site_header_default.json
  src/stories/views/components/site_header/fixtures/site_header_default_no_sticky.json
  src/stories/views/components/site_header/fixtures/site_header_mit_submenu_asFlyout_no_sticky.json
  src/stories/views/components/site_header/fixtures/site_header_mit_submenu_as_flyout.json
  src/stories/views/components/site_header/fixtures/site_header_mit_submenu_as_flyout_no_sticky.json
  src/stories/views/components/site_header/fixtures/site_header_mit_top_topics.json
  src/stories/views/components/site_header/fixtures/site_header_mit_top_topics_no_sticky.json
  src/stories/views/components/site_header/fixtures/site_header_mit_warnung.json
  src/stories/views/components/site_header/fixtures/site_header_mit_warnung_no_sticky.json
  src/stories/views/components/site_header/header.stories.js
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_column.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
Labels: minor

#635 Dpe 2316
  src/stories/views/components/button/top_topics_button.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_top_topics.hbs
Labels: bug

#638 Feature/dpe 2211
  src/assets/css/custom-components.css
  src/assets/fixtures/navigation/breadcrumb/breadcrumb.inc.json
  src/assets/fixtures/navigation/breadcrumb/breadcrumb_2_level.json
  src/assets/fixtures/navigation/breadcrumb/breadcrumb_3_level.json
  src/assets/fixtures/navigation/breadcrumb/breadcrumb_4_level.json
  src/assets/fixtures/navigation/breadcrumb/breadcrumb_5_level.json
  src/assets/fixtures/navigation/breadcrumb/breadcrumb_items.inc.json
  src/stories/views/components/base/load_dynamic.hbs
  src/stories/views/components/navigation/breadcrumb/breadcrumb.hbs
  src/stories/views/components/navigation/breadcrumb/breadcrumb.mdx
  src/stories/views/components/navigation/breadcrumb/breadcrumb.stories.js
  src/stories/views/components/navigation/breadcrumb/breadcrumb_items.ssi.hbs
  src/stories/views/components/navigation/breadcrumb/fixtures/breadcrumb_2_level.json
  src/stories/views/components/navigation/breadcrumb/fixtures/breadcrumb_3_level.json
  src/stories/views/components/navigation/breadcrumb/fixtures/breadcrumb_4_level.json
  src/stories/views/components/navigation/breadcrumb/fixtures/breadcrumb_5_level.json
  src/stories/views/components/navigation/breadcrumb/utils/breadcrumb_link_classes.hbs
Labels: minor

#639 Feature/dpe 2211
  src/stories/views/components/navigation/breadcrumb/breadcrumb.hbs
Labels: patch

#640 Chore/dpe 2320
  build/handlebars/helpers/handlebar-helpers.js
  package.json
  tailwind.config.js
  yarn.lock
Labels: internal

#636 fixed Flyout problemns for all kind of Flyouts
  src/assets/vendor/js/header.alpine.js
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_column.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
Labels: bug

#641 checked if is Cluster
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
Labels: bug

#642 Paging auf Indexseiten in Storybook bauen - FIX PROBLEMS - DPE-2079
  src/stories/views/components/button/components/button_label.hbs
  src/stories/views/components/button/utilities/button_dimension_classes.hbs
  src/stories/views/components/page/page_pagination.stories.js
  src/stories/views/components/pagination/pagination_button_left.hbs
  src/stories/views/components/pagination/pagination_button_left_linked.hbs
  src/stories/views/components/pagination/pagination_button_right.hbs
  src/stories/views/components/pagination/pagination_button_right_linked.hbs
  src/stories/views/components/pagination/pagination_current_page_invalid.hbs
  src/stories/views/components/pagination/pagination_more_than_three_pages.hbs
  src/stories/views/components/pagination/pagination_only_three_pages.hbs
  src/stories/views/components/pagination/pagination_only_two_pages.hbs
  tailwind.config.js
Labels: bug

#645 BUGFIX: fixes a the data model so that it
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/teaser/components/teaser_comments.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_comments.json
  src/stories/views/components/teaser/fixtures/teaser_comments_without_teaserinfo.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_comments.json
Labels: minor

#646 Bugfix/dpe 2330
  src/stories/views/components/button/components/button_label.hbs
  src/stories/views/components/button/utilities/button_dimension_classes.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_top_topics.hbs
  src/stories/views/components/teaser/tabbox/group_tabbox.hbs
  src/stories/views/components/teaser/tabbox/teaser_tabbox.hbs
  tailwind.config.js
Labels: minor
