Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-02, with the labels that each got.

#515 adds threshold for chromatic screenshots
  src/stories/views/components/teaser/podcast/podcast.stories.mdx
  src/stories/views/components/teaser/teaser_alternativ.stories.mdx
  src/stories/views/components/teaser/teaser_poster.stories.mdx
  src/stories/views/components/teaser/teaser_stage.stories.mdx
  src/stories/views/components/teaser/teaser_standard.stories.mdx
  src/stories/views/components/teaser/teaser_standard_av.stories.mdx
  src/stories/views/components/teaser/teaser_standard_event.stories.mdx
Labels: tests

#519 Dpe 2058
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
  src/stories/views/components/teaser/podcast/podcast_title.hbs
Labels: bug

#520 reverts diff layouts for shorttext
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
Labels: minor

#521 bugfix Label bylineText
  src/assets/css/custom-components.css
  src/stories/views/components/label/label.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/components/teaser_heading.hbs
Labels: bug

#524 better positioning of menuitem title and icons
  src/stories/views/components/content_nav/content_nav_item.hbs
Labels: bug

#525 fixes lineheight in dropdown button and items
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
Labels: bug

#526 cosmetics
  src/stories/views/components/content_nav/content_nav_item.hbs
Labels: bug

#527 oh mann ey
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
Labels: bug

#529 better css for search input with accented grp
  src/assets/css/custom-components.css
Labels: bug

#530 adds class to grp-ts-accented
  src/stories/views/components/teaser/group_teaser/group_teaser_accented.hbs
Labels: bug

#531 dedicated class for mixed input
  src/assets/css/custom-components.css
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_container.hbs
Labels: bug

#532 FEATURE: appendToDefault helper puts empty string between defaultValue and context.
  build/handlebars/helpers/handlebar-helpers.js
  src/stories/views/components/button/components/button_icon.hbs
Labels: patch

#534 BUGFIX: Adds white background color to grid_group_wrapper_classes
  src/stories/views/components/grid/grid_group_wrapper_classes.hbs
  tailwind.config.js
Labels: bug

#536 REFAC: Updates chromatic build script to run
  .github/workflows/chromatic.yml
Labels: skip-release

#538 fixes line-clamp in podcast title
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_title.hbs
Labels: bug

#539 uses realTeaserSize for podcast Title now
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
Labels: bug

#540 realTeaserSize for podcast Image
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
Labels: bug

#542 Dpe 2086 - Abstände Ortslabel einheitlich
  src/stories/views/components/button/button_round_classes.hbs
  src/stories/views/components/geoTag/geoTag.hbs
Labels: bug

#541 Bugfix/dpe 1863
  src/assets/css/custom-utilities.css
  src/stories/views/components/event/calendar/event_calendar_components.stories.mdx
  src/stories/views/components/event/calendar/event_calendar_event_teaser.hbs
  src/stories/views/components/event/filtererDs.feature.js
  src/stories/views/components/grid/grid_group_highlight.hbs
  src/stories/views/components/grid/grid_group_tabbed.hbs
  src/stories/views/components/grid/grid_group_wrapper_classes.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster.stories.mdx
  src/stories/views/components/teaser/content_nav/teaser_content_nav.stories.mdx
  src/stories/views/components/teaser/group_teaser/group.stories.mdx
  src/stories/views/components/teaser/podcast/podcast.stories.mdx
  src/stories/views/components/teaser/teaser_alternativ.stories.mdx
  src/stories/views/components/teaser/teaser_alternativ_av.stories.mdx
  src/stories/views/components/teaser/teaser_event_calendar.stories.mdx
  src/stories/views/components/teaser/teaser_indextext.stories.mdx
  src/stories/views/components/teaser/teaser_logic/teaser_logic.stories.mdx
  src/stories/views/components/teaser/teaser_poster.stories.mdx
  src/stories/views/components/teaser/teaser_stage.hbs
  src/stories/views/components/teaser/teaser_standard.stories.mdx
  src/stories/views/components/teaser/teaser_standard_av.stories.mdx
  src/stories/views/components/teaser/teaser_standard_event.stories.mdx
  tailwind.config.js
Labels: bug

#543 BUGFIX: Fixes the layout of standard 100%
  src/stories/views/components/teaser/teaser_standard.hbs
Labels: bug

#544 DPE-2095: padding for tabteaser needs tobe 9.5 so sm:px-9.5 is used
  .github/workflows/chromatic.yml
  src/stories/views/components/teaser/tabbox/group_tabbox.hbs
  src/stories/views/components/teaser/tabbox/teaser_tabbox.hbs
Labels: bug

#548 Bugfix/dpe 2073
  build/handlebars/helpers/handlebar-helpers.js
  src/stories/views/components/label/label_byline.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
Labels: bug

#550 BUGFIX: set context for airdate
  src/stories/views/components/teaser/components/teaser_byline.hbs
Labels: bug

#552 Bugfix/dpe 2100
  build/handlebars/helpers/handlebar-helpers.js
  src/stories/views/components/teaser/components/teaser_body.hbs
Labels: bug

#551 added Podcast channel Titel to !isSingleChannel
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
Labels: bug

#553 adds hash to comment link if commented
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/base/link_open.hbs
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_comments.json
  src/stories/views/components/teaser/fixtures/teaser_comments_without_teaserinfo.json
  src/stories/views/components/teaser/fixtures/teaser_standard_hero_serif_comments.json
Labels: bug

#554 changes md: to sm: in artice class
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
Labels: bug

#555 removes uppercase in bylines and in json titles
  src/assets/fixtures/teaser/cluster_teaser_Podcast_Channel.json
  src/assets/fixtures/teaser/headline_list_item.inc.json
  src/stories/views/components/teaser/cluster/teaser_cluster_byline.hbs
  src/stories/views/components/teaser/components/teaser_byline.hbs
  src/stories/views/components/teaser/fixtures/cluster_teaser_Podcast_Channel.json
Labels: bug

#556 Feature/dpe 2097: Add brand colors for media_button and labels
  src/assets/tailwind.css
  src/stories/views/components/mediaplayer/media_player.hbs
  src/stories/views/components/teaser/components/teaser_image.hbs
  tailwind.config.js
Labels: minor

#560 BUGFIX: Cluster-Teaser-Items gets text-decoration underline
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
Labels: minor

#561 BUGFIX: Prefixess all partial properties
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs
  src/stories/views/components/site_header/navigation_flyout/navigation_flyout_column.hbs
Labels: minor

#549 Bugfix: Externer-Link-Icon bricht in neue Zeile um
  src/stories/views/components/teaser/components/teaser_text.hbs
Labels: bug

#562 adds pos relative / z-100 to comments link span
  src/stories/views/components/teaser/components/teaser_comments.hbs
Labels: bug

#564 hide geotag for 25% Teaser
  src/stories/views/components/geoTag/geoTag.hbs
Labels: bug

#566 adds my-6 to highlight container
  src/stories/views/components/grid/grid_group_highlight.hbs
Labels: bug

#565 BUGFIX: Channel in Podcast Playlist Player do flu into Title
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
Labels: bug

#567 text-4xl for mobile group titles
  src/stories/views/components/teaser/group_teaser/group_teaser.hbs
  src/stories/views/components/teaser/group_teaser/group_teaser_accented.hbs
Labels: bug

#568 blue.science for --color-media-button
  src/assets/tailwind.css
Labels: bug

#571 Titel bricht um, wenn man Video startet bei 25% Teasern
  src/stories/views/components/teaser/components/teaser_body.hbs
Labels: bug

#576 Feature/dpe 2091: Ticket-Button in Modal gets tracked
  src/stories/views/components/event/event_ticket_button.hbs
  src/stories/views/components/modal/modal.feature.js
  src/stories/views/components/modal/modal.hbs
  src/stories/views/components/page/fixtures/page.json
Labels: minor
