Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-08, with the labels that each got.

#691 Dpe 2259 2
  src/assets/brand/_default/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.merged.json
  src/assets/brand/hr-bigband/conf/locatags.merged.json
  src/assets/brand/hr-fernsehen/conf/locatags.merged.json
  src/assets/brand/hr-inforadio/conf/locatags.merged.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.merged.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.merged.json
  src/assets/brand/hr-werbung/conf/locatags.merged.json
  src/assets/brand/hr/conf/locatags.merged.json
  src/assets/brand/hr1/conf/locatags.merged.json
  src/assets/brand/hr2/conf/locatags.merged.json
  src/assets/brand/hr3/conf/locatags.merged.json
  src/assets/brand/hr4/conf/locatags.merged.json
  src/assets/brand/you-fm/conf/locatags.merged.json
  src/assets/css/custom-utilities.css
  src/assets/fixtures/footer/footer_hessenschau.json
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/suche-ds.svg
  src/assets/icons/icons/svgmap/twitter-ds.svg
  src/assets/tailwind.css
  src/stories/views/components/dataPolicySettings/dataPolicySettingsDs.feature.js
  src/stories/views/components/dataPolicySettings/data_policy_settings.hbs
  src/stories/views/components/externalService/datapolicyCookie.subfeature.js
  src/stories/views/components/footer/fixtures/footer_hessenschau.json
  src/stories/views/components/footer/page_footer_content.hbs
  src/stories/views/components/footer/page_footer_social_media.hbs
  src/stories/views/components/forms/toggle_button.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
  tailwind.config.js
Labels: minor

#695 Dpe 2259 3
  src/stories/views/components/dataPolicySettings/data_policy_settings.hbs
  src/stories/views/components/footer/page_footer_column.hbs
  src/stories/views/components/footer/page_footer_nav_link.hbs
Labels: bug

#700 Feature/dpe 2445
  .storybook/preview.js
  package.json
  src/stories/InstallAndUpdateDependencies.mdx
  src/stories/InstallInDelivery.mdx
Labels: documentation

#701 Feature/dpe 2446
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: documentation

#696 DPE-2259 4
  build/handlebars/helpers/handlebar-helpers.js
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/rss-ds.svg
  src/assets/icons/icons/svgmap/x-ds.svg
  src/assets/tailwind.css
  src/stories/views/components/dataPolicySettings/dataPolicySettingsDs.feature.js
  src/stories/views/components/dataPolicySettings/data_policy_settings.hbs
  src/stories/views/components/footer/page_footer.hbs
  src/stories/views/components/footer/page_footer_column.hbs
  src/stories/views/components/footer/page_footer_content.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
  tailwind.config.js
Labels: bug

#705 BUGFIX: External links in section navigation render an incorrect url
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
Labels: bug

#706 more padding for footer if site has radioplayer
  src/assets/tailwind.css
Labels: bug

#707 subscribe button right below shorttext instead of own flex row
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
  src/stories/views/components/teaser/podcast/podcast_subscribe_button.hbs
Labels: patch

#709 Dpe 2259 7 some small fixes
  build/handlebars/helpers/handlebar-helpers.js
  src/assets/brand/you-fm/icons/logo/brandlogo--footer-desk.min.svg
  src/assets/brand/you-fm/icons/logo/brandlogo--footer.min.svg
  src/assets/brand/you-fm/icons/logo/svgmap.min.svg
  src/assets/brand/you-fm/icons/logo/svgmap/brandlogo--footer-desk.svg
  src/assets/brand/you-fm/icons/logo/svgmap/brandlogo--footer.svg
  src/assets/tailwind.css
  src/stories/views/components/footer/page_footer_logo.hbs
Labels: bug

#712 Dpe 2222 podcast episode player 2
  src/assets/brand/_default/conf/locatags.json
  src/assets/brand/hessenschau/conf/locatags.merged.json
  src/assets/brand/hr-bigband/conf/locatags.merged.json
  src/assets/brand/hr-fernsehen/conf/locatags.merged.json
  src/assets/brand/hr-inforadio/conf/locatags.merged.json
  src/assets/brand/hr-rundfunkrat/conf/locatags.merged.json
  src/assets/brand/hr-sinfonieorchester/conf/locatags.merged.json
  src/assets/brand/hr-werbung/conf/locatags.merged.json
  src/assets/brand/hr/conf/locatags.merged.json
  src/assets/brand/hr1/conf/locatags.merged.json
  src/assets/brand/hr2/conf/locatags.merged.json
  src/assets/brand/hr3/conf/locatags.merged.json
  src/assets/brand/hr4/conf/locatags.merged.json
  src/assets/brand/you-fm/conf/locatags.merged.json
  src/assets/brand/you-fm/icons/logo/svgmap.min.svg
  src/assets/fixtures/article/components/podcast/podcast_player_episode.json
  src/assets/fixtures/teaser/teasers.inc.json
  src/stories/views/components/article/components/podcast/fixtures/podcast_player_episode.json
  src/stories/views/components/article/components/podcast/podcast_player_episode.hbs
  src/stories/views/components/article/components/podcast/podcast_player_episode.mdx
  src/stories/views/components/article/components/podcast/podcast_player_episode.stories.js
  src/stories/views/components/article/components/podcast/podcast_player_playlist.hbs
  src/stories/views/components/content/content_footer/content_footer.hbs
  src/stories/views/components/page/fixtures/page.json
  src/stories/views/components/podcast/components/podcast_downloadbutton.hbs
  src/stories/views/components/podcast/components/podcast_item_title.hbs
  src/stories/views/components/podcast/components/podcast_playbutton.hbs
  src/stories/views/components/podcast/components/podcast_player_shorttext.hbs
  src/stories/views/components/podcast/components/podcast_player_ui.hbs
  src/stories/views/components/podcast/components/podcast_playlist_shorttext.hbs
  src/stories/views/components/podcast/components/podcast_subscribe_button.hbs
  src/stories/views/components/podcast/components/podcast_timedisplay.hbs
  src/stories/views/components/podcast/components/podcast_title.hbs
  src/stories/views/components/podcast/podcast_player.hbs
  src/stories/views/components/podcast/podcast_playlist_player.hbs
  src/stories/views/components/podcast/podcast_subscribe_button.mdx
  src/stories/views/components/podcast/podcast_subscribe_button.stories.js
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_50.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_playlist.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_playlist_50.json
  src/stories/views/components/teaser/podcast/podcast-playlist.hbs
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast.stories.js
Labels: minor
