Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-03, with the labels that each got.

#577 FEATURE: Podcasts Episodes Teaser Standard and alternative gets autho…
  src/stories/views/components/teaser/components/teaser_byline.hbs
  src/stories/views/components/teaser/components/teaser_byline_airdate.hbs
Labels: minor

#578 no white spaces in accent group
  src/stories/views/components/content_nav/content_nav_list.hbs
Labels: bug

#581 Bugfix/dpe 2182
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
Labels: bug

#583 Bugfix/dpe 2186
  build/handlebars/helpers/handlebar-helpers.js
  src/stories/views/components/modal/modal.hbs
Labels: bug

#584 adds isValid as a boolean for clusterTeaser
  src/assets/fixtures/teaser/teaser_cluster.inc.json
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
  src/stories/views/components/teaser/fixtures/cluster_teaser_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_100_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_100_image.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33_image.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_33_long_title.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50_genre.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_50_image.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_Podcast_Channel.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_extern_50.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_100.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_33.json
  src/stories/views/components/teaser/fixtures/cluster_teaser_ordered_50.json
Labels: bug

#586 BUGFIX: Mask string for trackingInfos
  src/stories/views/components/modal/modal.hbs
Labels: bug

#589 Documentation for Teaser-Heading
  src/stories/views/components/teaser/components/teaser_heading.stories.mdx
Labels: minor

#590 Dpe 1605
  src/stories/views/components/teaser/components/teaser_text.stories.mdx
Labels: minor

#592 Bugfix/dpe 2198 z indexes sometimes clash with old navi
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_list.hbs
Labels: bug

#593 forgot to edit custom-components.css
  src/assets/css/custom-components.css
Labels: bug

#594 - added hidden Text to section Nav Items for screenreaders/SEO
  src/assets/fixtures/site_header/sectionNavigation.inc.json
  src/assets/fixtures/site_header/sectionNavigation_mit_submenu.inc.json
  src/stories/views/components/site_header/fixtures/site_header_default.json
  src/stories/views/components/site_header/fixtures/site_header_mit_submenu.json
  src/stories/views/components/site_header/fixtures/site_header_mit_warnung.json
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
Labels: bug

#597 DOC: Adds documentation for the installation and
  .storybook/preview.js
  README.md
  src/stories/InstallAndUpdate.stories.mdx
Labels: documentation
