Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-09, with the labels that each got.

#717 Reactivates PianoHelper in clickTracking.feature
  src/stories/views/base/tracking/clickTracking.feature.js
Labels: minor

#720 FEATURE: piano tracking is used in podcast_player.alpine.js
  src/assets/vendor/js/podcast_player.alpine.js
  src/assets/vendor/js/podcast_player.alpine.new.js
Labels: patch

#718 adds a minimal json for socialmedia
  src/assets/fixtures/article/components/podcast/podcast_player_episode.json
  src/assets/fixtures/article/components/podcast/podcast_player_playlist.json
  src/assets/fixtures/socialsharing/socialsharing.inc.json
  src/stories/views/components/article/components/podcast/fixtures/podcast_player_episode.json
  src/stories/views/components/article/components/podcast/fixtures/podcast_player_playlist.json
  src/stories/views/components/article/components/podcast/podcast_episode_article.hbs
  src/stories/views/components/article/components/podcast/podcast_playlist_article.hbs
Labels: patch

#721 Feature: Remove unused atiHelper
  src/stories/views/base/tracking/atiHelper.subfeature.js
  src/stories/views/base/tracking/atiMediaHelper.subfeature.js
  src/stories/views/components/dataPolicySettings/dataPolicySettingsDs.feature.js
  src/stories/views/components/event/filtererDs.feature.js
  src/stories/views/components/event/nativeScrollDs.feature.js
  src/stories/views/components/mediaplayer/mediaplayerLoader.feature.js
  src/stories/views/components/modal/modal.feature.js
  src/stories/views/components/socialmedia/socialmediaCompact.feature.js
Labels: patch

#722 BUGFIX: teaserSize property is camelcased
  src/stories/views/components/mediaplayer/mediaplayerLoader.feature.js
Labels: bug

#723 Bugfix: set empty htmlProperties to make sure
  src/stories/views/components/mediaplayer/mediaplayer_button.hbs
  src/stories/views/components/teaser/components/teaser_av_consumption_close_button.hbs
  src/stories/views/components/teaser/ticker/teaser_ticker_body.hbs
Labels: bug

#724 FEATURE: label footer and quicksearch-form
  src/stories/views/components/footer/page_footer.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
Labels: minor

#727 - some color fixes for hrfernsehen & hrwerbung
  src/assets/brand/hr-werbung/icons/logo/brandlogo--desk.min.svg
  src/assets/brand/hr-werbung/icons/logo/brandlogo--mobile.min.svg
  src/assets/brand/hr-werbung/icons/logo/svgmap.min.svg
  src/assets/brand/hr-werbung/icons/logo/svgmap/brandlogo--desk.svg
  src/assets/brand/hr-werbung/icons/logo/svgmap/brandlogo--mobile.svg
  src/assets/brand/hr/icons/logo/svgmap.min.svg
  src/assets/brand/you-fm/icons/logo/svgmap.min.svg
  src/assets/tailwind.css
Labels: patch

#729 - fixes search border in footer with FF
  src/stories/views/components/dataPolicySettings/data_policy_settings.hbs
  src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
Labels: bug
