Repository mumprod/hr-design-system-handlebars, pull requests merged in 2023-01, with the labels that each got.

#456 move @click to wrapper instead of buttons
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
Labels: minor

#454 Dpe 1976 dom unnötig tief podcast playlist
  src/stories/views/components/teaser/podcast/podcast_downloadbutton.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
Labels: minor

#458 removes unnessesary px/mx in several wrappers
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
Labels: bug

#459 adds margin-bottom to nav when dropdown
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
Labels: bug

#464 DPE-1994
  src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
Labels: bug

#465 realTeaserSize for DPE-1982
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/teaser_poster.hbs
Labels: patch

#468 DPE-2002 - Fehler bei Akzentuiergruppen
  src/stories/views/components/teaser/group_teaser/group_teaser_accented.hbs
Labels: bug, patch

#471 Dpe 1947 podcast channel player 50% layout 768px
  .storybook/preview.js
  src/stories/views/components/teaser/podcast/podcast-playlist.hbs
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast.stories.mdx
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
Labels: bug

#472 Dpe 1981 ff
  src/stories/views/components/content_nav/content_nav.hbs
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
Labels: bug

#473 Responsive image configs for teasers in Tabbox
  src/assets/fixtures/teaser/teaser_group_tabbox.inc.json
  src/assets/fixtures/teaser/teaser_images.inc.json
  src/stories/views/components/teaser/fixtures/teaser_index.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_tabbox.json
  src/stories/views/components/teaser/fixtures/teaser_tabbox.json
Labels: bug

#474 removes unneeded margin bottom
  src/stories/views/components/content_nav/content_nav.hbs
Labels: bug

#475 Dpe 1981 ffff
  src/stories/views/components/content_nav/content_nav_container.hbs
Labels: bug

#476 edit inline-switch to match delivery
  src/stories/views/components/teaser/podcast/podcast.hbs
  src/stories/views/components/teaser/podcast/podcast_player.hbs
Labels: bug

#470 DPE-2003 Abstand von erster Gruppe funktioniert nicht bei 2x50%
  src/stories/views/components/grid/grid.hbs
  src/stories/views/components/grid/grid_group_highlight.hbs
  src/stories/views/components/grid/grid_group_standard.hbs
  src/stories/views/components/grid/grid_group_tabbed.hbs
  src/stories/views/components/grid/grid_group_wrapper_classes.hbs
  src/stories/views/components/page/page.hbs
  src/stories/views/components/teaser/tabbox/teaser_tabbox.hbs
Labels: bug

#477 truncate button-text in ClusterTeaser & Tabbox
  src/stories/views/components/button/button_pseudo.inc.hbs
  src/stories/views/components/teaser/tabbox/group_tabbox.hbs
Labels: bug

#480 Dpe 2013 podcast start not via tab but via leertaste
  src/stories/views/components/teaser/podcast/podcast_playbutton.hbs
Labels: bug

#481 FEATURE: Removes unneccessary div in teaser_image and fixes css problems
  src/stories/views/components/mediaplayer/media_player.hbs
  src/stories/views/components/teaser/components/teaser_body.hbs
  src/stories/views/components/teaser/components/teaser_image.hbs
  src/stories/views/components/teaser/teaser_alternativ.hbs
  src/stories/views/components/teaser/teaser_standard.hbs
Labels: minor

#482 bugfix geoTag
  src/stories/views/components/mediaplayer/media_player.hbs
  src/stories/views/components/teaser/components/teaser_lead.hbs
Labels: bug

#484 BUGFIX: Do not display group if no items available DPE-2017
  src/assets/fixtures/teaser/teaser_groups.inc.json
  src/stories/views/components/teaser/fixtures/teaser_group_100.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_contentnav.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight_2.json
  src/stories/views/components/teaser/fixtures/teaser_group_related_content_100.json
  src/stories/views/components/teaser/fixtures/teaser_index.json
  src/stories/views/components/teaser/group_teaser/group_teaser.hbs
  src/stories/views/components/teaser/group_teaser/group_teaser_accented.hbs
Labels: minor

#487 Dpe 2007 fokuszustände definieren
  src/assets/css/custom-components.css
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
  src/stories/views/components/content_nav/content_nav_item.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs
  src/stories/views/components/teaser/podcast/podcast_downloadbutton.hbs
  src/stories/views/components/teaser/podcast/podcast_item_title.hbs
  src/stories/views/components/teaser/podcast/podcast_playbutton.hbs
  src/stories/views/components/teaser/podcast/podcast_player.hbs
  src/stories/views/components/teaser/podcast/podcast_player_ui.hbs
  src/stories/views/components/teaser/podcast/podcast_subscribe_button.hbs
  src/stories/views/components/teaser/podcast/podcast_title.hbs
  src/stories/views/components/teaser/tabbox/group_tabbox.hbs
  src/stories/views/components/teaser/tabbox/teaser_tabbox.hbs
  tailwind.config.js
Labels: enhancement

#489 display the arrow in Ghostbutton (in DEV)
  src/stories/views/components/button/button_pseudo.hbs
Labels: bug

#491 BUGFIX: Run turbosnap only on push
  .github/workflows/chromatic.yml
Labels: skip-release

#492 FEATURE: Updates the ardplayer
  src/assets/fixtures/audio/audios.inc.json
  src/assets/fixtures/video/videos.inc.json
  src/assets/vendor/ardplayer/ardplayer-hr-6.3.11.79310671.css
  src/assets/vendor/ardplayer/ardplayer-hr-6.3.11.c442fe17.js
  src/assets/vendor/ardplayer/ardplayer-hr-6.3.4.4fc164e9.css
  src/assets/vendor/ardplayer/ardplayer-hr-6.3.4.8ea4ea3d.js
  src/assets/vendor/ardplayer/ardplayer-libimsc.179db74a.chunk.js
  src/assets/vendor/ardplayer/ardplayer-libimsc.304b8154.chunk.js
  src/assets/vendor/ardplayer/ardplayer-pluginchromecast.68c280ed.chunk.js
  src/assets/vendor/ardplayer/ardplayer-plugindash.a7275c59.chunk.js
  src/assets/vendor/ardplayer/ardplayer-pluginhls.f615d5a2.chunk.js
  src/assets/vendor/ardplayer/ardplayer-pluginhtmla.d04cedbb.chunk.js
  src/assets/vendor/ardplayer/ardplayer-pluginhtmlv.4f6a1291.chunk.js
  src/assets/vendor/ardplayer/ardplayer-pluginhtmlv.866c1fbf.chunk.js
  src/assets/vendor/ardplayer/ardplayer-sandlibrary.a58cd041.chunk.js
  src/assets/vendor/ardplayer/ardplayer-vendors~pluginchromecast.1fb1b290.chunk.js
  src/assets/vendor/ardplayer/ardplayer-vendors~pluginchromecast~plugindash~pluginhls~pluginhtmla~pluginhtmlv.a52f1cc9.chunk.js
  src/assets/vendor/ardplayer/ardplayer-vendors~plugindash.446f5c07.chunk.js
  src/assets/vendor/ardplayer/ardplayer-vendors~pluginhls.ab9656f5.chunk.js
  src/assets/vendor/ardplayer/ardplayer-vendors~pluginhtmla.aadd9d24.chunk.js
  src/assets/vendor/ardplayer/ardplayer-vendors~pluginhtmla~pluginhtmlv.08e5de97.chunk.js
  src/stories/views/components/mediaplayer/ardPlayerLoader.subfeature.js
  src/stories/views/components/teaser/fixtures/cluster_teaser_Podcast_Channel.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_100_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_50_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_alternative_hero_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_group_100 copy.json
  src/stories/views/components/teaser/fixtures/teaser_group_100.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight.json
  src/stories/views/components/teaser/fixtures/teaser_group_100_highlight_2.json
  src/stories/views/components/teaser/fixtures/teaser_group_related_content_100.json
  src/stories/views/components/teaser/fixtures/teaser_index.json
  src/stories/views/components/teaser/fixtures/teaser_podcast.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_50.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_playlist.json
  src/stories/views/components/teaser/fixtures/teaser_podcast_playlist_50.json
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_audio_livestream.json
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_podcast.json
  src/stories/views/components/teaser/fixtures/teaser_standard_25_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_audio.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_audio_livestream.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_live.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_podcast.json
  src/stories/views/components/teaser/fixtures/teaser_standard_50_serif_video.json
  src/stories/views/components/teaser/fixtures/teaser_tabbox.json
Labels: minor

#493 use realTeaserSize in ClusterTeaser
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
  src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
Labels: bug

#495 Dpe 2007 2
  src/assets/css/custom-components.css
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_shorttext.hbs
  src/stories/views/components/teaser/podcast/podcast_subscribe_button.hbs
  src/stories/views/components/teaser/podcast/podcast_title.hbs
Labels: enhancement

#497 fixed margins and paddings for indextext and accented group
  src/stories/views/components/teaser/group_teaser/group_teaser_accented.hbs
  src/stories/views/components/teaser/teaser_indextext.hbs
Labels: bug

#498 add ring-0 to ds-link-inset @ :not(:focus-visible)
  src/assets/css/custom-components.css
Labels: bug

#502 moves click.outside to nav element
  src/stories/views/components/content_nav/content_nav_container.hbs
  src/stories/views/components/content_nav/content_nav_dropdown.hbs
Labels: bug

#505 new icon for "extern"
  src/assets/icons/icons/svgmap.min.svg
  src/assets/icons/icons/svgmap/extern.svg
  src/stories/views/components/teaser/components/teaser_text.hbs
  src/stories/views/components/teaser/stage/stage_text.hbs
Labels: enhancement

#506 refactoring teaser text
  src/stories/views/components/teaser/components/teaser_text.hbs
Labels: enhancement

#509 FEATURE: cluster-teaser uses svgs from
  src/assets/brand/hessenschau/icons/logo/svgmap.min.svg
  src/assets/brand/hessenschau/icons/logo/svgmap/hessenschau_de.svg
  src/assets/brand/hessenschau/icons/logo/svgmap/sportschau.svg
  src/assets/brand/hessenschau/icons/logo/svgmap/tagesschau_de.svg
  src/assets/icons/cluster-teaser/svgmap.min.svg
  src/assets/icons/cluster-teaser/svgmap/boerse_ard_de.svg
  src/assets/icons/cluster-teaser/svgmap/hessenschau_de.svg
  src/assets/icons/cluster-teaser/svgmap/tagesschau_de.svg
  src/stories/views/components/teaser/cluster/teaser_cluster.hbs
Labels: minor

#510 DPE-2044
  src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
Labels: bug

#512 realTeaserSize & String for Switch statement
  src/stories/views/components/page/page.hbs
  src/stories/views/components/teaser/podcast/podcast_playlist_player.hbs
Labels: bug
