Repository mumprod/hr-design-system-handlebars, pull requests merged in 2024-05, with the labels that each got.

#917 Socail sharing code improvements 2
  src/stories/views/components/page/index/page_test_story.hbs
  src/stories/views/components/page/story/story_article.hbs
  src/stories/views/components/site_header/mainNavigationHandler.alpine.js
  src/stories/views/components/social_sharing/social_sharing_compact.hbs
  src/stories/views/components/social_sharing/social_sharing_compact.stories.js
  src/stories/views/components/social_sharing/social_sharing_compact_icons.hbs
Labels: bug

#926 :sparkles: Podcast Episode Page uses
  src/stories/views/components/page/podcast/podcast_episode_article.hbs
  src/stories/views/components/page/story/fixtures/story_with_label.json
  src/stories/views/components/page/story/story_main.stories.js
Labels: minor

#930 fixes bottom position of sharing button in mobile view
  src/stories/views/components/site_header/mainNavigationHandler.alpine.js
  src/stories/views/components/social_sharing/social_sharing_compact.hbs
Labels: bug

#924 general line heigt 1.5 in copytext
  src/stories/views/components/content/copytext/components/paragraph/paragraph_body.hbs
  src/stories/views/components/page/index/page.stories.js
Labels: bug

#931 :bug: Make sure that the regex in the loca helper only matches when it recognizes numbers in between opening and closing curly braces.
  .storybook/preview.js
  build/handlebars/helpers/handlebar-helpers.js
Labels: bug

#932 updates async-alpine to latest version
  yarn.lock
Labels: dependencies

#933 Try to make chromatic take screenshots of the opened modal by inserti…
  src/stories/views/components/modal/modal.stories.js
Labels: bug

#934 add appendix
  src/assets/fixtures/page/story/story.inc.json
  src/stories/views/components/base/link.hbs
  src/stories/views/components/button/link_button.hbs
  src/stories/views/components/button/link_button.stories.js
  src/stories/views/components/button/utilities/button_variation_classes.hbs
  src/stories/views/components/geoTag/geotag_collection.hbs
  src/stories/views/components/page/components/appendix.hbs
  src/stories/views/components/page/components/appendix.mdx
  src/stories/views/components/page/components/appendix.stories.js
  src/stories/views/components/page/story/fixtures/story.json
  src/stories/views/components/page/story/fixtures/story_with_label.json
  src/stories/views/components/page/story/fixtures/story_with_square_image.json
  src/stories/views/components/page/story/story_article.hbs
  src/stories/views/components/program_reference/program_reference.hbs
  src/stories/views/components/topictag/topictag_collection.hbs
Labels: minor
