Repository mumprod/hr-design-system-handlebars, pull requests merged in 2024-02, with the labels that each got.

#827 :bug: Add support for statically generated navigation on error pages
  src/stories/views/components/site_header/section_navigation/section_navigation.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/service_navigation/service_list.hbs
Labels: minor

#829 Bugfix/2829
  src/stories/views/components/base/link.hbs
  src/stories/views/components/base/link.stories.js
Labels: minor

#832 Bugfix/2829
  src/stories/views/base/tracking/pianoHelper.subfeature.js
  src/stories/views/components/base/link.hbs
Labels: minor

#834 :bug: Make data policy overlay display
  src/stories/views/components/dataPolicySettings/data_policy_settings.hbs
Labels: minor

#845 :bug: Fix the check for the existence of the
  src/stories/views/base/tracking/pianoHelper.subfeature.js
Labels: minor

#846 add size and variant controls to icon storys
  src/stories/views/components/button/button.stories.js
Labels: documentation

#853 :bug: use globalSettingsCookie instead of incompatible trackingCookie.
  src/stories/views/components/mediaplayer/ardPlayerLoader.subfeature.js
Labels: minor

#856 :bug: Update auto package to it's latest version to solve the issue from https://github.com/intuit/auto/issues/2425
  package.json
  yarn.lock
Labels: patch

#859 :recycle: remove structuredData.ssi because it is not longer used
  src/assets/brand/you-fm/icons/logo/svgmap.min.svg
  src/assets/fixtures/content/copytext/copytext.json
  src/assets/fixtures/content/copytext/copytext_additionalInfo.json
  src/assets/fixtures/content/copytext/copytext_cite.json
  src/assets/fixtures/content/copytext/copytext_downloadbox.json
  src/assets/fixtures/content/copytext/copytext_faq.json
  src/assets/fixtures/content/copytext/copytext_filedownload.json
  src/assets/fixtures/content/copytext/copytext_image.json
  src/assets/fixtures/content/copytext/copytext_infobox.json
  src/assets/fixtures/content/copytext/copytext_jobposting.json
  src/assets/fixtures/content/copytext/copytext_paragraph.inc.json
  src/assets/fixtures/content/copytext/copytext_podcastepisode.json
  src/assets/fixtures/content/copytext/copytext_posterteaser.json
  src/stories/views/components/content/copytext/components/contentbox/fixtures/contentbox.json
  src/stories/views/components/content/copytext/copytext.hbs
  src/stories/views/components/content/copytext/fixtures/copytext.json
  src/stories/views/components/content/copytext/fixtures/copytext_additionalInfo.json
  src/stories/views/components/content/copytext/fixtures/copytext_cite.json
  src/stories/views/components/content/copytext/fixtures/copytext_downloadbox.json
  src/stories/views/components/content/copytext/fixtures/copytext_faq.json
  src/stories/views/components/content/copytext/fixtures/copytext_filedownload.json
  src/stories/views/components/content/copytext/fixtures/copytext_image.json
  src/stories/views/components/content/copytext/fixtures/copytext_infobox.json
  src/stories/views/components/content/copytext/fixtures/copytext_jobposting.json
  src/stories/views/components/content/copytext/fixtures/copytext_podcastepisode.json
  src/stories/views/components/content/copytext/fixtures/copytext_posterteaser.json
  src/stories/views/components/page/podcast/podcast_episode-webview.hbs
  src/stories/views/components/page/podcast/podcast_episode.hbs
  src/stories/views/components/page/podcast/podcast_playlist.hbs
  src/stories/views/components/page/story/fixtures/story.json
Labels: bug

#860 Implemented 'layout: fullscreen' parameter in Storybook configuration…
  src/stories/views/components/page/story/story_main.stories.js
Labels: enhancement
