Repository mumprod/hr-design-system-handlebars, pull requests merged in 2024-03, with the labels that each got.

#872 💄 DPE-2938 -Mobile Ansicht Logo und Burger-Icon nicht auf Linie
  src/assets/css/custom-utilities.css
  src/stories/views/components/site_header/brand_navigation/brand_navigation.hbs
  src/stories/views/components/site_header/brand_navigation/brand_navigation_item.hbs
  src/stories/views/components/site_header/header.hbs
  src/stories/views/components/site_header/mainNavigationHandler.alpine.js
  src/stories/views/components/site_header/section_navigation/section_navigation.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
  src/stories/views/components/site_header/section_navigation/section_navigation_top_topics.hbs
  src/stories/views/components/site_header/service_navigation/service_navigation.hbs
Labels: patch

#877 add json for external services
  src/assets/fixtures/content/copytext/copytext_externalservice.json
  src/assets/fixtures/external_service/external_service.inc.json
  src/stories/views/components/content/copytext/components/externalservice.hbs
  src/stories/views/components/content/copytext/copytext.stories.js
  src/stories/views/components/content/copytext/fixtures/copytext_externalservice.json
Labels: enhancement

#876 added parameter to component call
  src/stories/views/components/site_header/header.hbs
Labels: bug

#878 Feature/dpe 2978
  .github/workflows/chromatic.yml
  .github/workflows/release.yml
  .nvmrc
  README.md
Labels: minor

#887 :bug: Configure theme in offline page
  build/handlebars/helpers/handlebar-helpers.js
  src/stories/views/components/page/index/page_offline.hbs
Labels: minor
